name: SHiFT Code Monitor

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests python-dotenv

      - name: Run SHiFT monitor
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python3 twitter_shift_scraper.py

      - name: Upload seen tweets
        uses: actions/upload-artifact@v4
        with:
          name: shift-codes-seen
          path: seen_tweets.txt
          retention-days: 30

      - name: Upload SHiFT log
        uses: actions/upload-artifact@v4
        with:
          name: shift-codes-log
          path: shift_codes_log.txt
          retention-days: 30
